# Generated by Django 3.2.8 on 2021-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('check_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='todo_list',
        ),
    ]
